### ISSUE TITLE
CPU usage is too high during training

### ISSUE THREAD

**Issue by Zmjcc** [MIC-DKFZ/basic_unet_example#9] opened 2019-12-28 05:47 UTC
When I was training with another dataset, I set the patch to 512. During the training, the CPU occupation rate was too high, but during the verification, the occupation rate was not that high. Can you give me some suggestions on how to reduce the CPU occupation rate during training? Thanks!

**Comment by elpequeno** [comment] 2020-01-10 10:50
Hi zmjcc, sorry for the delay, I was out of office. 
What do you mean by "too high". How is the CPU occupation on your own dataset different compared to the example dataset? Are you training on CPU or GPU?

**Comment by elpequeno** [comment] 2020-01-30 16:14
Any update on this one?

**Comment by elpequeno** [comment] 2020-02-10 09:07
As I am not 100% sure what the problem is and if it is still there, I will close this issue. If this problem still exists, please reopen it.

**Closed as completed by elpequeno** 2020-02-10 09:07 UTC
